/**
 * The reference machine's GPU divider — generated by tools/gpu-reciprocal.mjs from the oracle
 * (_oracle/probe_gpu_division.gd, Intel(R) Iris(R) Xe Graphics); do not edit by hand.
 *
 * Vulkan allows a division to be off by a few ULP, and this GPU computes a / b as a × rcp(b) with a
 * hardware reciprocal (proved on 2016 quotients). particles.glsl decides which particle restarts
 * in a step with such a quotient (index / amount): where the reciprocal is not the correctly rounded
 * one, a particle due exactly on a step boundary starts a step earlier or later. The offsets below
 * (in ULP, for 1/n with n ≤ 1024) are those reciprocals; every other 1/n — and 1/x for
 * the lifetimes the game uses, measured equal — is the correctly rounded value.
 */
const F = Math.fround;
const f32 = new Float32Array(1);
const u32 = new Uint32Array(f32.buffer);

/** n → ULP offset of the GPU's 1/n from F(1/n). */
const RECIPROCAL_ULP_OFFSETS = new Map([[7,-1],[13,-1],[14,-1],[15,-1],[23,-1],[26,-1],[28,-1],[30,-1],[33,-1],[35,-1],[37,-1],[46,-1],[52,-1],[56,-1],[60,-1],[63,-1],[66,-1],[67,1],[70,-1],[74,-1],[89,-1],[91,-1],[92,-1],[104,-1],[112,-1],[117,-1],[119,-1],[120,-1],[126,-1],[132,-1],[133,-1],[134,1],[139,-1],[140,-1],[148,-1],[178,-1],[179,1],[181,-1],[182,-1],[184,-1],[189,1],[195,-1],[208,-1],[219,1],[221,-1],[224,-1],[234,-1],[238,-1],[240,-1],[241,-1],[243,1],[252,-1],[255,-1],[261,1],[264,-1],[266,-1],[268,1],[278,-1],[280,-1],[289,-1],[293,1],[296,-1],[307,1],[309,-1],[327,-1],[343,-1],[345,-1],[349,-1],[355,1],[356,-1],[358,1],[362,-1],[364,-1],[368,-1],[378,1],[390,-1],[397,1],[409,-1],[413,-1],[416,-1],[419,-1],[421,-1],[425,1],[427,1],[438,1],[439,-1],[442,-1],[448,-1],[455,-1],[468,-1],[471,-1],[476,-1],[480,-1],[482,-1],[486,1],[504,-1],[510,-1],[515,-1],[519,-1],[521,1],[522,1],[525,1],[528,-1],[532,-1],[535,-1],[536,1],[543,-1],[547,-1],[555,-1],[556,-1],[560,-1],[563,-1],[575,-1],[578,-1],[583,-1],[586,1],[592,-1],[614,1],[618,-1],[619,-1],[625,1],[631,-1],[654,-1],[661,1],[685,1],[686,-1],[690,-1],[698,-1],[699,-1],[705,1],[710,1],[712,-1],[716,1],[724,-1],[728,-1],[736,-1],[741,1],[749,-1],[756,1],[763,-1],[779,-1],[780,-1],[794,1],[818,-1],[819,-1],[821,-1],[823,-1],[826,-1],[827,-1],[832,-1],[838,-1],[842,-1],[850,1],[854,1],[876,1],[878,-1],[884,-1],[896,-1],[907,-1],[910,-1],[936,-1],[942,-1],[952,-1],[960,-1],[964,-1],[972,1],[987,-1],[1008,-1],[1020,-1]]);

/** The GPU's single-precision 1/x. O(1). */
export function gpuReciprocal(x) {
  const correct = F(1 / F(x));
  const offset = Number.isInteger(x) ? RECIPROCAL_ULP_OFFSETS.get(x) : undefined;
  if (offset === undefined) return correct;
  f32[0] = correct;
  u32[0] += offset;
  return f32[0];
}

/** The GPU's a / b: F(a × rcp(b)). O(1). */
export function gpuDivide(a, b) {
  return F(F(a) * gpuReciprocal(b));
}
